### ISSUE TITLE
Protector all chests in certain regions

### ISSUE THREAD

**Issue by dark22** [Adventure-Terraria-Server-Project/Protector-Plugin#45]
Please consider adding command for protect all chests of certain regions, just as /refillchestmany protecting chests of certain places.

**Thank for this great plugin!**

**Comment by antagonist99** [comment]
It would be an interesting function since protecting chests in a region would make it simpler than manually, 

Just we already have is a way to remove protections within regions. Vote yes.

**Comment by CoderCow** [comment]
It's only really worth the effort if those chests are hard or impossible to be manually protected for some reason. Like if you want to protect all chests in a large part of the entire world (e.g. all underground chests).
If you just need to protect a bunch of chests in a small area at once, then the perma modes of the commands (like /pt +p or /rchest +p) should be simple enough.

**Comment by tanpro260196** [comment]
One vote from me... :) I don't really care about underground cabin chest. But I want to mass-protect and mass-refill chests from jungle shrine and tree.
